/**
 * Where the endpoint backend's conversations actually live.
 *
 * ## Why this exists when `session-index.ts` says peek stores no transcripts
 *
 * That rule is about **conversations that already have an owner**. An ACP
 * conversation is written by Claude Code or Codex into their own history; a
 * second copy in peek would be a second answer to "what does the model
 * remember", and only one of them can be right. Nothing here changes that: the
 * ACP backend still stores nothing.
 *
 * The endpoint backend has no agent process. There is no `.jsonl` anywhere, no
 * `session/list` to call, no other party that could be asked. Not storing here
 * does not mean "one copy of the history" — it means **zero**, and it meant
 * exactly that until this file existed: closing a chat tab dropped the `Agent`
 * instance and the conversation with it.
 *
 * So the dividing line is not "does peek persist" but "does this conversation
 * already have an owner". Zed draws it in the same place and arrived there
 * independently — external ACP agents' transcripts are not in its database at
 * all, its own agent's are. See
 * `docs/design/2026-08-03-chat-history-ownership.md` §1.2.
 *
 * ## Shape
 *
 * One file per conversation, `<dir>/<sessionId>.json`. Not one big file: a
 * corrupt write damages one conversation instead of the catalogue, and every
 * save touches only the conversation that changed. Not SQLite either — peek has
 * no such dependency, and the only query this ever needs ("newest first") is
 * already answered by the route index in memory. See §3.2.
 *
 * ## Failure posture
 *
 * Identical to `SessionIndex`, and for the same reason: a chat panel that opens
 * an empty conversation is recoverable, one that refuses to open because a file
 * is unreadable is not. Every read failure degrades to `null`; writes are
 * temp-file + rename so a crash mid-write cannot leave a torn file behind.
 */

import { mkdirSync, readFileSync, renameSync, rmSync, unlinkSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import type { AgentMessage } from '@earendil-works/pi-agent-core'
import { noopLogger, type ChatMessage, type Logger } from '@peek/core'

const FILE_VERSION = 1

/**
 * Subdirectory of `~/.peek/chat` this backend's conversations live in.
 *
 * A sibling of the ACP agents' working directories (`acp/profiles.ts`'s
 * `workdirSegment`), and separated for the same reason: nothing should ever be
 * in a position to enumerate another backend's files.
 */
export const ENDPOINT_THREAD_DIR = 'endpoint'

/**
 * One stored conversation.
 *
 * ## Why two lists and not one
 *
 * `transcript` is what the user reads; `messages` is what the model remembers.
 * They are not two copies of one thing — after a compaction they are *supposed*
 * to differ — and neither can be derived from the other without loss:
 * `AgentMessage` has no notion of a tool call's display title, of where a
 * thinking block ended, of an attachment receipt or of a stop reason, and
 * rebuilding those by guesswork would put a second, untested translator on the
 * one path nobody exercises until something has already gone wrong.
 *
 * This is not the "two histories" the ACP argument rejects. Those two are
 * written by two processes at two different times under two different rules.
 * These two are written by one function at one instant into one file: there is
 * no window in which one is updated and the other is not.
 */
export interface EndpointThreadFile {
  version: typeof FILE_VERSION
  sessionId: string
  /** The transcript, as the window shows it. */
  transcript: ChatMessage[]
  /** The model's own context, fed back to `Agent` as `initialState.messages`. */
  messages: AgentMessage[]
  /** Which model this conversation was held with. Redundant with the route; kept for triage. */
  modelId: string
  updatedAt: number
}

export class EndpointThreadStore {
  readonly #dir: string
  readonly #log: Logger

  constructor(dir: string, logger: Logger = noopLogger) {
    this.#dir = dir
    this.#log = logger
  }

  get dir(): string {
    return this.#dir
  }

  path(sessionId: string): string {
    // `sessionId` is generated by `randomUUID`, never by anything outside this
    // process — but this path is joined against a directory and then written to,
    // so the assumption is checked rather than trusted. A traversal here would
    // be a write anywhere on disk.
    if (!/^[A-Za-z0-9_-]+$/.test(sessionId)) {
      throw new Error(`Refusing to build a thread path from ${JSON.stringify(sessionId)}.`)
    }
    return join(this.#dir, `${sessionId}.json`)
  }

  /** The stored conversation, or `null` when there is none peek can read. */
  read(sessionId: string): EndpointThreadFile | null {
    let raw: string
    try {
      raw = readFileSync(this.path(sessionId), 'utf8')
    } catch {
      return null // Absent is the normal case for a conversation nobody resumed.
    }
    try {
      const parsed = JSON.parse(raw) as Partial<EndpointThreadFile>
      // A version peek does not know is not a file to guess at, for the same
      // reason `SessionIndex` refuses one: reading a future shape wrongly loses
      // the conversation, while declining to read it loses nothing that was not
      // already unreachable.
      if (parsed.version !== FILE_VERSION) return null
      if (!Array.isArray(parsed.transcript) || !Array.isArray(parsed.messages)) return null
      return {
        version: FILE_VERSION,
        sessionId,
        transcript: parsed.transcript as ChatMessage[],
        messages: parsed.messages as AgentMessage[],
        modelId: typeof parsed.modelId === 'string' ? parsed.modelId : '',
        updatedAt: typeof parsed.updatedAt === 'number' ? parsed.updatedAt : 0,
      }
    } catch (error) {
      // Truncated or corrupt. Degrade, do not throw — but **say so**. Silently
      // reading `null` here is indistinguishable from "there was no such
      // conversation", and the two could not be further apart from the user's
      // side: one is a tab that was never opened, the other is history that
      // existed this morning and is now gone. The file stays where it is.
      this.#log.log('warn', `the stored conversation ${sessionId} could not be parsed and was skipped`, error)
      return null
    }
  }

  /**
   * Store one conversation.
   *
   * Returns whether it landed. Callers use that to decide whether to advertise
   * the conversation in the catalogue: a route with no readable file behind it
   * is the ghost row this whole design exists to avoid.
   */
  write(file: Omit<EndpointThreadFile, 'version'>): boolean {
    const target = this.path(file.sessionId)
    const temp = `${target}.tmp`
    const body: EndpointThreadFile = { version: FILE_VERSION, ...file }
    try {
      mkdirSync(this.#dir, { recursive: true, mode: 0o700 })
      writeFileSync(temp, JSON.stringify(body), { encoding: 'utf8', mode: 0o600 })
      renameSync(temp, target)
      return true
    } catch (error) {
      this.#log.log('warn', `the conversation ${file.sessionId} could not be stored`, error)
      try {
        unlinkSync(temp)
      } catch {
        /* Nothing to clean up. */
      }
      return false
    }
  }

  /**
   * Delete one conversation's body.
   *
   * `true` when the file is gone afterwards — including when it was never there,
   * which is the same outcome from the caller's point of view. `false` means it
   * is still on disk, and the caller must **not** drop the route: a route
   * removed while the file survives leaves a conversation nobody can attribute
   * and nobody can delete.
   */
  remove(sessionId: string): boolean {
    try {
      rmSync(this.path(sessionId), { force: true })
      return true
    } catch (error) {
      this.#log.log('warn', `the conversation ${sessionId} could not be deleted`, error)
      return false
    }
  }
}
